# Built with Jekyll 3.2.0

# Setup
title:               หลักสูตร Python 3 boot camp
tagline:             'software development with python 3'
description:         'เริ่มต้นเรียนรู้ การเขียนโปรแกรมด้วยภาษา python'
url:                 'http://itbakery.github.io'
baseurl:             '/python3tutorial'

# About/contact
author:
  name:              Sawangpong Muadphet
  url:               https://twitter.com/sawangpong_
  email:             sawangpong@itbakery.net

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
highlighter: rouge
